// <auto-generated />
using System;
using CNUCoin.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CNUCoin.DAL.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250311203406_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CNUCoin.DAL.Common.Entities.Block", b =>
                {
                    b.Property<Guid>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BlockChainHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastHashDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MinerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlockId");

                    b.HasIndex("AssignedById");

                    b.HasIndex("MinerId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("CNUCoin.DAL.Common.Entities.Member", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsMiner")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("CNUCoin.DAL.Common.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("AssignedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FromId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("AssignedById");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CNUCoin.DAL.Common.Entities.Wallet", b =>
                {
                    b.Property<Guid>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WalletId");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CNUCoin.DAL.Common.Entities.Block", b =>
                {
                    b.HasOne("CNUCoin.DAL.Common.Entities.Member", "AssignedBy")
                        .WithMany("BlocksAssigned")
                        .HasForeignKey("AssignedById")
                        .IsRequired();

                    b.HasOne("CNUCoin.DAL.Common.Entities.Member", "Miner")
                        .WithMany("BlocksMained")
                        .HasForeignKey("MinerId")
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("Miner");
                });

            modelBuilder.Entity("CNUCoin.DAL.Common.Entities.Transaction", b =>
                {
                    b.HasOne("CNUCoin.DAL.Common.Entities.Member", "AssignedBy")
                        .WithMany("TransactionsAssigned")
                        .HasForeignKey("AssignedById")
                        .IsRequired();

                    b.HasOne("CNUCoin.DAL.Common.Entities.Member", "From")
                        .WithMany("TransactionsFrom")
                        .HasForeignKey("FromId")
                        .IsRequired();

                    b.HasOne("CNUCoin.DAL.Common.Entities.Member", "To")
                        .WithMany("TransactionsTo")
                        .HasForeignKey("ToId")
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("CNUCoin.DAL.Common.Entities.Wallet", b =>
                {
                    b.HasOne("CNUCoin.DAL.Common.Entities.Member", "Owner")
                        .WithOne("Wallet")
                        .HasForeignKey("CNUCoin.DAL.Common.Entities.Wallet", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CNUCoin.DAL.Common.Entities.Member", b =>
                {
                    b.Navigation("BlocksAssigned");

                    b.Navigation("BlocksMained");

                    b.Navigation("TransactionsAssigned");

                    b.Navigation("TransactionsFrom");

                    b.Navigation("TransactionsTo");

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
